.TH RNUM 1 2022-05-15 GNU

.SH NAME
rnum \- Random Number Generator

.SH SYNOPSIS
.B rnum
\fBRANGE\fR
[\fBBASE\fR]
[\fB\-r\fR \fImax\fR]
[\fB\-l\fR]
[\fB\-b\fR \fImin\fR]

.SH DESCRIPTION
.B rnum
is a small util that generates a 'random' number up to the value that is passed to it.

.SH OPTIONS
.TP
.B \-r, \-\-range \fImax
sets the ceiling for the number generation
.TP
.B \-b, \-\-base \fImin
sets the base for the number generation
.TP
.B \-l, \-\-legacy
return instead of printing to stdout (legacy mode)

.SH NOTES
Per default
.B rnum
used to return the generated number, however now that is hidden behind the -l flag
or the --enable-legacy configure option.

.SH AUTHOR
zockerfreunde03/z0gg3r <zockerfreunde03.info@gmx.de>
